// <auto-generated />
using GraphQLProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLProject.Migrations
{
    [DbContext(typeof(GraphQLDbContext))]
    partial class GraphQLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQLProject.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = "2023-09-11 10:30 AM",
                            Description = "Meeting with team to discuss project status.",
                            Title = "Meeting Notes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = "2023-09-12 02:15 PM",
                            Description = "List of tasks to complete this week.",
                            Title = "Task List"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = "2023-09-13 04:00 PM",
                            Description = "Brainstorming session for new project ideas.",
                            Title = "Ideas"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = "2023-09-14 08:00 AM",
                            Description = "Grocery shopping list for the weekend.",
                            Title = "Shopping List"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = "2023-09-15 09:30 AM",
                            Description = "Outline for the upcoming project.",
                            Title = "Project Outline"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
